DROP TABLE IF EXISTS fleet_price;
DROP TABLE IF EXISTS fleet;
DROP TRIGGER IF EXISTS INSERT_FLEET_TOKEN;
DELETE FROM user WHERE type in ('FLEET', 'SALE');

CREATE TABLE fleet (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(5) NOT NULL DEFAULT '',
    name VARCHAR(128) NOT NULL DEFAULT '',
    setup INT NOT NULL DEFAULT 0,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE fleet_price (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    price FLOAT NOT NULL,
    type ENUM('WASH', 'OIL', 'WASH_OIL'),
    fleet_id INT NOT NULL,
    FOREIGN KEY (fleet_id) REFERENCES fleet(id)
);

DELIMITER $$
CREATE TRIGGER INSERT_FLEET_TOKEN BEFORE INSERT ON fleet FOR EACH ROW
BEGIN
    DECLARE id INT DEFAULT 0;

    SELECT AUTO_INCREMENT INTO id FROM information_schema.tables
    WHERE TABLE_NAME = 'fleet' and TABLE_SCHEMA = database();

    SET NEW.token = UPPER(SUBSTRING(SHA2(id, 256), 32, 5));
END $$
DELIMITER ;

ALTER TABLE user CHANGE type type ENUM('RESIDENTIAL', 'BUSINESS', 'EGOBIE', 'SALE', 'FLEET');

INSERT INTO user (type, username, password, email, phone_number) VALUES
('SALE', 'bd1', 'bc254388680ed7c7e426b417e81f41b6af7ef319', 'bdsale1@egobie.com', '2019120383');